In [2]:
import pandas as pd
import numpy as np

# Step 1: Create dataset manually (same as CSV)
data = pd.DataFrame({
    "Age": [25,30,35,40,45,50,23,27,33,48,52,29,31,37,42],
    "Income": [40000,50000,60000,80000,90000,100000,38000,42000,58000,85000,110000,46000,52000,62000,78000],
    "SpendingScore": [60,65,70,30,25,20,75,80,68,22,18,72,66,55,35]
})

X = data.values

# Step 2: Parameters
k = 3
max_iters = 100

# Step 3: Initialize centroids
np.random.seed(42)
random_indices = np.random.choice(len(X), k, replace=False)
centroids = X[random_indices]

# Distance function
def euclidean_distance(a, b):
    return np.sqrt(np.sum((a - b) ** 2))

# Step 4: K-Means
for _ in range(max_iters):
    clusters = [[] for _ in range(k)]

    # Assign points
    for point in X:
        distances = [euclidean_distance(point, centroid) for centroid in centroids]
        cluster_index = np.argmin(distances)
        clusters[cluster_index].append(point)

    # Update centroids
    new_centroids = []
    for cluster in clusters:
        if len(cluster) == 0:
            new_centroids.append(centroids[len(new_centroids)])
        else:
            new_centroids.append(np.mean(cluster, axis=0))

    new_centroids = np.array(new_centroids)

    # Stop if converged
    if np.allclose(centroids, new_centroids):
        break

    centroids = new_centroids

# Step 5: Output
print("Final Centroids:\n", centroids)

print("\nCluster Sizes:")
for i, cluster in enumerate(clusters):
    print(f"Cluster {i+1}: {len(cluster)} points")

Final Centroids:
 [[4.61666667e+01 9.05000000e+04 2.50000000e+01]
 [3.32000000e+01 5.64000000e+04 6.48000000e+01]
 [2.60000000e+01 4.15000000e+04 7.17500000e+01]]

Cluster Sizes:
Cluster 1: 6 points
Cluster 2: 5 points
Cluster 3: 4 points
